version: 0.0
os: linux
files:
  - source: /test/browser
    destination: /opt/pfa

hooks:
  BeforeInstall:
    - location: scripts/backup.sh
      timeout: 180
      runas: root

  AfterInstall:
    - location: scripts/restart-server.sh
      timeout: 300
      runas: root
