version: 0.0
os: linux
files:
  - source: /test/browser
    destination: /usr/share/nginx/html/

hooks:
  BeforeInstall:
    - location: scripts/remove_old_file.sh
      timeout: 180
      runas: root

  AfterInstall:
    - location: scripts/restart-server.sh
      timeout: 300
      runas: root
