version: 0.0
os: linux
files:
  - source: /dist/test/browser
    destination: /usr/share/nginx/html/
hooks:
  AfterInstall:
    - location: scripts/restart-server.sh
      timeout: 300
      runas: root
