version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing source NPM dependencies...
      - npm ci
      - npm install -g @angular/cli

  build:
    commands:
      - echo Build started on `date`
      - ng build
      - cp appspec.yml dist/  # Copy appspec.yml to dist folder
      
artifacts:
  files:
    - '**/*'
    - scripts/**/*
    - appspec.yml  # Ensure this is in dist/ before packaging
  base-directory: 'dist/'
  discard-paths: yes
