version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18 # Specify your Node.js version if needed
    commands:
      - echo Installing source NPM dependencies...
      - npm ci
      - npm install -g @angular/cli

  build:
    commands:
      - echo Build started on `date`
      - ng build
      
artifacts:
  files:
    - '**/*'
    - scripts/**/*
    - appspec.yml
  base-directory: 'dist/'
  discard-paths: yes
