version: 0.2
phases:
  install:
    commands:
      - echo "Upgrading glibc to meet Node.js requirements"
      - yum -y groupinstall "Development Tools"
      - yum -y install gcc wget make
      - wget http://ftp.gnu.org/gnu/libc/glibc-2.28.tar.gz
      - tar -xvf glibc-2.28.tar.gz
      - cd glibc-2.28
      - mkdir build
      - cd build
      - ../configure --prefix=/opt/glibc-2.28
      - make -j$(nproc)
      - make install
      - export LD_LIBRARY_PATH=/opt/glibc-2.28/lib:$LD_LIBRARY_PATH
      - export PATH=/opt/glibc-2.28/bin:$PATH
      - cd ../../
      - rm -rf glibc-2.28*
      - npm install -g @angular/cli
  pre_build:
    commands:
      - npm install -f
  build:
    commands:
      - ng build
artifacts:
  files:
    - '**/*'
  base-directory: dist/test/server
