version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing source NPM dependencies...
      - npm ci
      - npm install -g @angular/cli

  build:
    commands:
      - echo Build started on `date`
      - ng build
      - echo Copying necessary files to the dist directory...
      - cp appspec.yml dist/              # Copy the appspec.yml to dist/
      - cp -r scripts dist/scripts        # Copy the entire scripts folder to dist/

artifacts:
  files:
    - '**/*'                  # Include all files in the dist directory
  base-directory: 'dist/'     # Set dist as the base directory for deployment
  discard-paths: no           # Preserve directory structure
